logging:
  config: config/log4j.properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transfer
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 2
    useSSL: false
    data: classpath:transfer.sql
    initialization-mode: always
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.hansk.tools.transfer.domain
transfer: #迁移相关相关配
  bos:
    accessKey:
    secretKey:
    endpoint: gz.bcebos.com
  wos:
    accessKeyId:
    accessKeySecret:
    endpoint: http://s3-cn-south-5.wcsapi.com
    region: cn-south-5
  #需要迁移bucket列表,可配置多项
  buckets:
    -
      #源存储
      originStorage: wos
      #源存储Bucket
      originBucket: video-upload
      #源存储所在区域，COS有效，默认值transfer.cos.region
      originRegion: cn-south-5
#      #源存储Endpoint，OSS WOS BOS有效，默认值transfer.oss.end_point
#      originEndPoint: http://oss-cn-beijing.aliyuncs.com
      #源存储加速域名，七牛有效，默认值bucket域名列表中任意一个
#      originCDNDomain: cdn.qiniu.domain
      #对象前缀,空遍历完整bucket
      prefix:
        - marathon-
      #目标存储，默认transfer.target
      targetStorage: bos
      #目标bucket，默认与源相同
      targetBucket: upload
      #目标存储所在区域，COS有效，默认值transfer.cos.region
      targetRegion: gz
#      #源存储Endpoint，OSS有效，默认值transfer.oss.end_point
#      targetEndPoint:
#      #暂时无效
#      targetCDNDomain:
#    -
#      originStorage: oss
#      originBucket:
#      targetBucket:

  #默认迁移存储目标,数组，当transfer.bucket[].targetStorage 空时，取细致
  target:
#    - cos

  #最小传输线程
  minTransThread: 2
  #最大传输线程
  maxTransThread: 100
  #检查对象存在的最大线程数
  maxCheckThread: 10
  #迁移transferBefore时间点之前的对象
  transferBefore: 2022-10-19 00:00:00